# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{- site.title -}}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{- site.myvariable -}}.
title: Isomer Pages Template
url: "https://www.tech.gov.sg" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
plugins:
  - jekyll-feed
  - jekyll-assets
  # - jekyll-paginate
  - jekyll-sitemap
  # - jekyll-paginate-v2
  # - sanitize
safe: false
exclude: [travis-script.js, .travis.yml, README.md, package.json, package-lock.json, test_suite, node_modules]

favicon: /assets/img/favicon.ico
google_analytics: UA-test

# Breadcrumbs
#breadcrumbs:
#  root:
#    hide: false  # show breadcrumbs on root/home page
#    image: false # Show image or title text

collections:
  application-guidelines:
    output: true
  who-we-are:
    output: true
  products-and-services:
    output: true
  events:
    output: true

# Resource Room and Pagination
resources_name: "resource_room"
paginate: 12

# Site configuration for Isomer Pages
##################################

# Custom CSS file path
custom_css_path: "/do-not-touch/theme-colors/custom.css"
custom_print_css_path: "/assets/css/print.css"

# Isomer recommender system - only works for simple-page, leftnav-page, and post
recommender: true

defaults:
  - scope:
      path: ""
    values:
      layout: "page"
