# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Isomer Pages Template
title-abbreviated: Isomer Pages
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  This website was built using the Isomer Design System and Jekyll
baseurl: "/isomerpages-template" # the subpath of your site, e.g. /blog
url: "https://isomerpages.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-assets
  # - jekyll-paginate
  - jekyll-sitemap
  # - jekyll-paginate-v2
  # - sanitize
safe: false


# Breadcrumbs
breadcrumbs:
  root:
    hide: false  # show breadcrumbs on root/home page
    image: false # Show image or title text

collections:
  application-guidelines:
    output: true
  who-we-are:
    output: true
  products-and-services:
    output: true

# Resource Room and Pagination
resources_name: "resource_room"
paginate: 12

# Site configuration for Isomer Pages
##################################

# Homepage sections
homepage_hero_i_want_to: false # if i_want_to is true, there will be no key highlights
homepage_programmes: true
homepage_resources: true
homepage_careers: true

# Feedback Form URL
feedback_form_url: "https://form.sg/#!/forms/govtech/5a9ce876b3a3b6006e6b8335"

# FAQ URL
faq_url: "http://www.ifaq.gov.sg/HLB/apps/Fcd_faqmain.aspx"
faq_url_external: true

# Custom CSS file path
custom_css_path: "/do-not-touch/theme-colors/custom.css"
custom_print_css_path: "/assets/css/print.css"

# ############################################################
# # Site configuration for the Jekyll 3 Pagination Gem
# # The values here represent the defaults if nothing is set
# pagination:
  
#   # Site-wide kill switch, disabled here it doesn't run at all 
#   enabled: true

#   # The default document collection to paginate if nothing is specified ('posts' is default)
#   collection: 'posts'

#   # How many objects per paginated page, used to be `paginate` (default: 0, means all)
#   per_page: 12

#   # The permalink structure for the paginated pages (this can be any level deep)
#   permalink: ':num.html' # Pages are index.html inside this folder (default)
#   #permalink: '/page/:num.html' # Pages are simple html files 
#   #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

#  # Optional,omit or set both before and after to zero to disable. 
#  # Controls how the pagination trail for the paginated pages look like. 
#   trail: 
#     before: 2
#     after: 2

#   # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
#   sort_field: 'date'

#   # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
#   sort_reverse: true

# ############################################################

# autopages:
#   enabled: false

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
